//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileApp.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MobileApp.Resources.Languages.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Data.
        /// </summary>
        internal static string AddData {
            get {
                return ResourceManager.GetString("AddData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car Number Plate.
        /// </summary>
        internal static string carnumberplate {
            get {
                return ResourceManager.GetString("carnumberplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide Car Number Plate.
        /// </summary>
        internal static string carnumberplateRequired {
            get {
                return ResourceManager.GetString("carnumberplateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to changelanguage.
        /// </summary>
        internal static string changelanguage {
            get {
                return ResourceManager.GetString("changelanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Civil Id Back side Image.
        /// </summary>
        internal static string civilidbacksideimagepath {
            get {
                return ResourceManager.GetString("civilidbacksideimagepath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Civil Id Expiry Date.
        /// </summary>
        internal static string civilidexpirydate {
            get {
                return ResourceManager.GetString("civilidexpirydate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Civil Id.
        /// </summary>
        internal static string civilidimagepath {
            get {
                return ResourceManager.GetString("civilidimagepath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Civil Id/Passport Number.
        /// </summary>
        internal static string civilidnumber {
            get {
                return ResourceManager.GetString("civilidnumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide Civil Id Number.
        /// </summary>
        internal static string civilidnumberRequired {
            get {
                return ResourceManager.GetString("civilidnumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        internal static string companyid {
            get {
                return ResourceManager.GetString("companyid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clicked {0} times.
        /// </summary>
        internal static string Counter {
            get {
                return ResourceManager.GetString("Counter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        internal static string dashboard {
            get {
                return ResourceManager.GetString("dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee.
        /// </summary>
        internal static string Employee {
            get {
                return ResourceManager.GetString("Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        internal static string enddate {
            get {
                return ResourceManager.GetString("enddate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter 4 Digit Pin.
        /// </summary>
        internal static string Enter4DigitPin {
            get {
                return ResourceManager.GetString("Enter4DigitPin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter PIN.
        /// </summary>
        internal static string enterpin {
            get {
                return ResourceManager.GetString("enterpin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiry Date.
        /// </summary>
        internal static string expirydate {
            get {
                return ResourceManager.GetString("expirydate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        internal static string fullname {
            get {
                return ResourceManager.GetString("fullname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name in English.
        /// </summary>
        internal static string fullnameen {
            get {
                return ResourceManager.GetString("fullnameen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide Full Name in English.
        /// </summary>
        internal static string fullnameenRequired {
            get {
                return ResourceManager.GetString("fullnameenRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide Full Name.
        /// </summary>
        internal static string fullnameRequired {
            get {
                return ResourceManager.GetString("fullnameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorized Gates.
        /// </summary>
        internal static string gateidstring {
            get {
                return ResourceManager.GetString("gateidstring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go Back.
        /// </summary>
        internal static string GoBack {
            get {
                return ResourceManager.GetString("GoBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has Vehicle?.
        /// </summary>
        internal static string hasvehicle {
            get {
                return ResourceManager.GetString("hasvehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello, World!.
        /// </summary>
        internal static string HelloWorld {
            get {
                return ResourceManager.GetString("HelloWorld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id Type.
        /// </summary>
        internal static string idtype {
            get {
                return ResourceManager.GetString("idtype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Active.
        /// </summary>
        internal static string isactive {
            get {
                return ResourceManager.GetString("isactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Blocked Person?.
        /// </summary>
        internal static string ispersonblocked {
            get {
                return ResourceManager.GetString("ispersonblocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Title.
        /// </summary>
        internal static string jobtitle {
            get {
                return ResourceManager.GetString("jobtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide Job Title.
        /// </summary>
        internal static string jobtitleRequired {
            get {
                return ResourceManager.GetString("jobtitleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to logout.
        /// </summary>
        internal static string logout {
            get {
                return ResourceManager.GetString("logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My QR.
        /// </summary>
        internal static string MyQr {
            get {
                return ResourceManager.GetString("MyQr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nationality.
        /// </summary>
        internal static string nationalityid {
            get {
                return ResourceManager.GetString("nationalityid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide Nationality.
        /// </summary>
        internal static string nationalityidRequired {
            get {
                return ResourceManager.GetString("nationalityidRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passport Number.
        /// </summary>
        internal static string passportnumber {
            get {
                return ResourceManager.GetString("passportnumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission.
        /// </summary>
        internal static string Permission {
            get {
                return ResourceManager.GetString("Permission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Picure.
        /// </summary>
        internal static string personalpicurepath {
            get {
                return ResourceManager.GetString("personalpicurepath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocked By.
        /// </summary>
        internal static string personblockedbyuserid {
            get {
                return ResourceManager.GetString("personblockedbyuserid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block End Date.
        /// </summary>
        internal static string personblockenddate {
            get {
                return ResourceManager.GetString("personblockenddate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block Start Date.
        /// </summary>
        internal static string personblockstartdate {
            get {
                return ResourceManager.GetString("personblockstartdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extend At.
        /// </summary>
        internal static string personextendat {
            get {
                return ResourceManager.GetString("personextendat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extend By.
        /// </summary>
        internal static string personextendbyuserid {
            get {
                return ResourceManager.GetString("personextendbyuserid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension End Date.
        /// </summary>
        internal static string personextentionenddate {
            get {
                return ResourceManager.GetString("personextentionenddate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: Please scan the QR code provided in your permission letter.
        /// </summary>
        internal static string QrScanNote {
            get {
                return ResourceManager.GetString("QrScanNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register with QR Code.
        /// </summary>
        internal static string RegisterWithQRCode {
            get {
                return ResourceManager.GetString("RegisterWithQRCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Data.
        /// </summary>
        internal static string RemoveData {
            get {
                return ResourceManager.GetString("RemoveData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Application.
        /// </summary>
        internal static string requestapplicationid {
            get {
                return ResourceManager.GetString("requestapplicationid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide Request Application.
        /// </summary>
        internal static string requestapplicationidRequired {
            get {
                return ResourceManager.GetString("requestapplicationidRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Personal Data.
        /// </summary>
        internal static string resetpersonaldata {
            get {
                return ResourceManager.GetString("resetpersonaldata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Vehicle Data.
        /// </summary>
        internal static string resetvehicledata {
            get {
                return ResourceManager.GetString("resetvehicledata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan QR.
        /// </summary>
        internal static string ScanQR {
            get {
                return ResourceManager.GetString("ScanQR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Pin.
        /// </summary>
        internal static string SetPin {
            get {
                return ResourceManager.GetString("SetPin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        internal static string startdate {
            get {
                return ResourceManager.GetString("startdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle.
        /// </summary>
        internal static string Vehicle {
            get {
                return ResourceManager.GetString("Vehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand.
        /// </summary>
        internal static string vehiclebrandid {
            get {
                return ResourceManager.GetString("vehiclebrandid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string vehiclecategoryid {
            get {
                return ResourceManager.GetString("vehiclecategoryid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color .
        /// </summary>
        internal static string vehiclecolorid {
            get {
                return ResourceManager.GetString("vehiclecolorid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Year.
        /// </summary>
        internal static string vehiclemodelid {
            get {
                return ResourceManager.GetString("vehiclemodelid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Vehicle Registration Image.
        /// </summary>
        internal static string vehicleregistrationimagepath {
            get {
                return ResourceManager.GetString("vehicleregistrationimagepath", resourceCulture);
            }
        }
    }
}
